Update user guide to ensure consistency
AY2425S1-CS2103T-W14-1/tp pull request #348
Opened 2024-11-10 16:48 UTC by ngjianyi

Closes #347

2024-11-10 17:03 UTC, LinkesV approved these changes
LGTM

2024-11-10 17:03 UTC, prave1n reviewed
Overall, looks more standardised. Some minor changes may be required

2024-11-10 17:03 UTC, prave1n commented on docs/UserGuide.md
> +- All parameters must be given.
there is only one parameter for this command which is `INDEX` so this may not be needed

2024-11-10 17:03 UTC, prave1n commented on docs/UserGuide.md
> +- At least one space is needed between parameters.
there is only one parameter for this command which is `INDEX` so this may not be needed

2024-11-10 17:03 UTC, prave1n commented on docs/UserGuide.md
> +- `SORT_ORDER`: The sorting order. It must be either `a` for ascending or `d` for descending, and cannot be blank.
should the parameter include so/ and sb/

2024-11-10 17:03 UTC, prave1n commented on docs/UserGuide.md
> +    - `SORT_ORDER` is case-sensitive.
since this is mentioned in the warnings, this may seem repetitive

2024-11-10 17:21 UTC, CJianzhi reviewed
LGTM! Just some minor errors that needs to be edited

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +Clears all data regarding suppliers and deliveries in vendor vault.
VendorVault should be used here

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +- To include multiple `TAG`/`PRODUCT`, use multiple `t/TAG`/`pro/PRODUCT` respectively.
I think it will look funny with the s behind tho in markdown

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +- `STATUS`: The suppler status to change to. It must be one of the following values: `active`, `inactive`, and cannot be blank.
Typo here for supplier

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +- Supplier at index 3 of the displayed list has status marked as `active`, assuming there is at least three suppliers displayed and the third supplier is not currently `INACTIVE`. Otherwise, an error
Should be not currently `ACTIVE`, and should the status marked as `active` be in caps as well

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +- All suppliers with `name` containing `link` and `COMPANY` containing `NU` is shown.
grammatical error, should use "are shown" i think

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +- `SORT_ORDER`: The sorting order. It must be either `a` for ascending or `d` for descending, and cannot be blank.
need add prefix in front for each parameter

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
>  **Warnings**:
Should we mention no duplicate parameters for all commands?

2024-11-10 17:21 UTC, CJianzhi commented on docs/UserGuide.md
> +- `SORT_BY`: The field to sort by. It must be either `c` for `COST`, `d` for `DELIVERY_DATE_TIME` or `s` for `STATUS`, and cannot be blank.
Parameter does not have prefix

2024-11-11 04:49 UTC, CJianzhi reviewed
LGTM!

2024-11-11 04:49 UTC, CJianzhi commented on docs/UserGuide.md
> +- Supplier at index 3 of the displayed list has status marked as `active`, assuming there is at least three suppliers displayed and the third supplier is not currently `inactive`. Otherwise, an error
I thought it should be the supplier that is active cannot be marked as  active again

2024-11-11 07:51 UTC, CJianzhi requested changes
LGTM! Some minor changes needed before merging

2024-11-11 07:51 UTC, CJianzhi commented on docs/UserGuide.md
> +  - e.g. If you have searched for suppliers using the `find` command, the sort command will not sort the previous results of the `find` command, but will sort all suppliers in VendorVault.
Should this be `find -s` command?

2024-11-11 07:51 UTC, CJianzhi commented on docs/UserGuide.md
>  - At least one space is needed between `-d` and `INDEX`.
Need to be updated for this point

2024-11-11 07:51 UTC, CJianzhi commented on docs/UserGuide.md
> +Sorts deliveries based on their cost, date and time, and status in VendorVault.
Should this be or instead of and?

2024-11-11 07:52 UTC, CJianzhi approved these changes
LGTM!

2024-11-11 07:56 UTC, merged